name: Psychics
version: $version
main: io.github.monun.psychics.plugin.PsychicsPlugin
author: Monun
api-version: 1.19
libraries:
  - io.github.monun:tap-core:4.9.4
  - io.github.monun:invfx-core:3.3.0
  - io.github.monun:kommand-core:3.1.3
